# Generated by Django 2.2.6 on 2019-11-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisbiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='data_alteracao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='data_criacao',
        ),
    ]
